// Kamera (Stufe 1, nur App) und der Calima-Look als Rezept in der Datei
export const CAMERA: Record<string, string> = {
  "Calima darf die Kamera nicht nutzen. Erlaube sie in den Einstellungen des iPhones unter Calima.": "Calima isn't allowed to use the camera. Allow it in the iPhone's Settings under Calima.",
  "Die Kamera lässt sich gerade nicht öffnen.": "The camera can't be opened right now.",
  "Das Foto ließ sich nicht aufnehmen. Versuch es noch einmal.": "The photo couldn't be taken. Try again.",
  "Loslassen bringt den Look zurück": "Let go to bring the look back",
  "Zoom {factor}": "Zoom {factor}",
  "Kamera öffnet …": "Opening camera …",
  Looks: "Looks",
  Auslösen: "Shutter",
  Rückkamera: "Back camera",
  Frontkamera: "Front camera",
  "{n} auf dem Stapel von heute. Einsortieren kannst du abends.": "{n} on today's stack. You can sort them in the evening.",
  "Halten zeigt das Original, Wischen macht heller oder dunkler.": "Hold to see the original, swipe to go brighter or darker.",
  "Mit einem Look zeigt Halten das Original. Wischen macht heller oder dunkler.": "With a look, hold to see the original. Swipe to go brighter or darker.",
  "Calima-Look": "Calima look",
  "{label} „{name}“ mitgenommen. Liegt oben bei „Deine Looks“.": "{label} “{name}” taken along. It's up under “Your looks”.",
  "Aus der Datei gelesen, in Calima nachempfunden": "Read from the file, approximated in Calima",
  "Aus der Datei gelesen, so wie das Foto gesichert wurde": "Read from the file, just as the photo was saved",
  "So fotografieren": "Shoot like this",
  "Für die Kamera brauchst du ein Konto. Mitgenommen ist der Look trotzdem.": "The camera needs an account. The look is taken along anyway.",
  "Das Foto liegt auf dem Stapel von heute.": "The photo is on today's stack.",
  "Die {n} Fotos liegen auf dem Stapel von heute.": "The {n} photos are on today's stack.",
  "Der Film liegt im Fotostudio.": "The film is in the photo studio.",
  "Entwickelt. Das Bild liegt auf dem Stapel seines Tages.": "Developed. The picture is on the stack for its day.",
  "Entwickelt. Die {n} Bilder liegen auf dem Stapel ihres Tages.": "Developed. The {n} pictures are on the stack for their day.",
  "Entwickelt. Die Bilder liegen auf dem Stapel ihres Tages.": "Developed. The pictures are on the stack for their day.",
  "Calima-Look mitnehmen": "Take the Calima look along",
  "Farbe und Licht ohne Zuschnitt, so wie das Foto gesichert wurde.": "Colour and light without the crop, just as the photo was saved.",
  // Film einlegen (Stufe 2)
  "Film, {i} von {n}": "Film, {i} of {n}",
  "{i} von {n}": "{i} of {n}",
  "Film einlegen": "Load film",
  "Film raus": "Film out",
  "Die Bilder siehst du erst nach dem Entwickeln. Voll ist der Film bei {n}; beiseitegelegt wartet er auf dich.": "You'll see the pictures only once the film is developed. It's full at {n}; set aside, it waits for you.",
  Beiseitelegen: "Set aside",
  // Werkzeug (E1)
  Werkzeug: "Tools",
  "Werkzeug weglegen": "Put tools away",
  Zeit: "Shutter",
  ISO: "ISO",
  Fokus: "Focus",
  Weiß: "White",
  Räder: "Dials",
  Brennweite: "Focal length",
  "echtes Objektiv": "real lens",
  "Ausschnitt aus der Hauptkamera": "Crop from the main camera",
  "Raster und Wasserwaage": "Grid and level",
  "Rad auf A, die Kamera stellt selbst": "Dial to A, the camera decides",
  "Schärfe von Hand, mit Lupe": "Manual focus, with loupe",
  Farbtemperatur: "Color temperature",
  Belichtungsmesser: "Light meter",
  "Ziehen auf dem Lineal dreht das Rad. A gibt es der Kamera zurück.": "Drag the ruler to turn the dial. A hands it back to the camera.",
  "Letztes Foto ansehen": "View last photo",
  "Schärfe und Licht stehen fest. Ein Tipp auf die Marke löst sie.": "Focus and exposure are locked. Tap the mark to release.",
  "Noch ein Tipp auf die Marke hält Schärfe und Licht fest.": "Tap the mark again to lock focus and exposure.",
  "Ziehen oder tippen wählt das Licht. Feinabstimmung verschiebt die Farbe wie bei Fuji.": "Drag or tap to pick the light. Fine-tune shifts the color like on a Fuji.",
  "Weiß messen": "Measure white",
  "Richte das Quadrat auf etwas Weißes oder Graues und drück den Auslöser. Es wird kein Foto gemacht.": "Aim the square at something white or grey and press the shutter. No photo is taken.",
  "Zu hell zum Messen. Stell Heller/Dunkler etwas dunkler oder nimm eine Stelle ohne Glanz.": "Too bright to measure. Turn Brighter/Darker down a little or pick a spot without glare.",
  "Zu dunkel zum Messen. Mehr Licht, oder stell Heller/Dunkler etwas heller.": "Too dark to measure. Add light, or turn Brighter/Darker up a little.",
  "Das sieht nicht weiß aus. Richte das Quadrat auf etwas Weißes oder Graues.": "That doesn't look white. Aim the square at something white or grey.",
  "Messen hat nicht geklappt. Versuch es noch einmal.": "Measuring didn't work. Try again.",
  "Filme · {n}": "Films · {n}",
  "nah|Fokus": "close",
  "Tisch|Fokus": "table",
  "Zimmer|Fokus": "room",
  "Straße|Fokus": "street",
  "Ziehen stellt scharf. Solange du ziehst, zeigt die Lupe die Mitte dreifach groß.": "Drag to focus. While you drag, the loupe shows the center three times larger.",
  "Lupe 3×": "Loupe 3×",
  Licht: "Light",
  gemessen: "measured",
  Feinabstimmung: "Fine-tune",
  röter: "redder",
  türkiser: "more cyan",
  blauer: "bluer",
  gelber: "more yellow",
  "etwas {a}": "a little {a}",
  " und etwas ": " and a little ",
  neutral: "neutral",
  Look: "Look",
  "Weißabgleich verschieben": "Shift white balance",
  "Werkzeug hervorholen": "Bring the tools back",
  "Werkzeug wegziehen, Sucher größer": "Pull the tools away for a bigger viewfinder",
  "{n} von Hand": "{n} manual",
  "alles auf A": "all on A",
  Fest: "Locked",
  "Letztes Foto": "Last photo",
  "Zurück zur Kamera": "Back to the camera",
  "{mm} mm ist ein Ausschnitt aus der Hauptkamera, kein eigenes Objektiv.": "{mm} mm is a crop from the main camera, not a lens of its own.",
  Entwickeln: "Develop",
  "Film „{name}“ weiter belichten, {i} von {n}": "Keep shooting film “{name}”, {i} of {n}",
  "{i}/{n}": "{i}/{n}",
  // Einwegkamera-Vorlagen (disposable.ts)
  Einwegkamera: "Disposable",
  "Einwegkamera, {i} von {n}": "Disposable camera, {i} of {n}",
  "Einwegkamera „{name}“ einlegen: {txt}": "Load disposable “{name}”: {txt}",
  "Einwegkamera: fester Ausschnitt, nichts einzustellen, jedes Bild mit Blitz. Entwickelt wird bei {n}.": "Disposable: fixed framing, nothing to set, flash on every shot. Develops at {n}.",
  "Einwegkamera: fester Ausschnitt, nichts einzustellen, ohne Blitz. Entwickelt wird bei {n}.": "Disposable: fixed framing, nothing to set, no flash. Develops at {n}.",
  Strandtag: "Beach Day",
  "warm und kräftig, ISO 800, mit Blitz": "warm and punchy, ISO 800, with flash",
  Sonnenhut: "Sun Hat",
  "hell und verwaschen wie in praller Sonne, ohne Blitz": "bright and washed out like full sun, no flash",
  Kiosk: "Corner Shop",
  "kühl, kräftiges Grün, mit Blitz": "cool, strong greens, with flash",
  Silberkorn: "Silver Grain",
  "Schwarzweiß mit sichtbarem Korn, mit Blitz": "black and white with visible grain, with flash",
  "Weiches Grau": "Soft Grey",
  "Schwarzweiß weich, feines Korn, mit Blitz": "soft black and white, fine grain, with flash",
  Großstadt: "Big City",
  "blass und hart, nur Rot bleibt, mit Blitz": "pale and hard, only red stays, with flash",
  Feldweg: "Country Lane",
  "natürlich und leicht gedämpft, mit Blitz": "natural and slightly muted, with flash",
  "Ohne Erlaubnis für die Mediathek liegen die Fotos nur in Calima. Erlauben kannst du es in den iPhone-Einstellungen unter Calima → Fotos.": "Without access to your library, the photos only live in Calima. You can allow it in the iPhone Settings under Calima → Photos.",
  "Blitz aus": "Flash off",
  "Blitz automatisch": "Flash auto",
  "Blitz an": "Flash on",
  "ausgelöst": "fired",
};
